### ISSUE TITLE
下载压缩包文件，下载下来损坏

### ISSUE THREAD

**Issue by 857076222** [otokaze/189Cloud-Downloader#1]
下了两次

**Comment by otokaze** [comment]
把文件链接给我下，我试试看能不能复现

**Comment by 857076222** [comment]
以访万一，我把它先utf8编码了下，见谅。https://cloud.189.cn/t/f63ymmYVB3ua%uFF08%u8BBF%u95EE%u7801%uFF1Aiut9%uFF09，我后来用了网盘客户端下，是可用的
@otokaze

**Comment by otokaze** [comment]
@857076222 已经修复了，当前最新版为v0.1.4，如果还不行的话，需要指定为单线程进行下载。 `get -c 1 <fileId>`
