### ISSUE TITLE
增加Android版本与纯黑色背景

### ISSUE THREAD

**Issue by soundsnow** [otokaze/189Cloud-Downloader#10]
官方版太肥了，非常费电，而且背景是纯白色
对于眼睛和OLED屏幕造成损伤比较大
添加并检测系统色，亮色和暗色（纯黑色），可以帮助OLED屏幕省电
请将最高SDK API定为Android 13/14，我不喜欢sdcard目录被一堆垃圾中国App自动创建一堆文件夹
@otokaze 它支持多个文件同时下载吗？官方的只有一次只能同时下载一个文件，遇到那种小文件批量下载会损失不少等待下一文件进入下载队列的时间，同时下载2/3/4/5/自定义，如果网络稳定且网速够高的话，总之就是避免下载的文件是损坏的
还有开启省电模式和电池优化并息屏的后台下载，包括通知栏进度条
自带英文，因为一般中文汉字占用的像素会比英文字母多
发布至Github与F-Droid开源应用商店
它能批量下载别人分享的文件吗？我手机端网页只允许下载一个
允许复制单个下载任务的URL网页链接到其他下载管理器，比如FDM，IDM

**Comment by soundsnow** [comment]
另外我还有个问题，没有账号到底能否下载文件？由于官方限制，网页必须登录才让下载，但是理论上是不是这样呢？我把登录后获得的链接复制到下载器是可以下载的
如果理论上支持免号下载的话，请加入此功能，一般仅用于下载别人分享的文件

**Comment by otokaze** [comment]
> 另外我还有个问题，没有账号到底能否下载文件？由于官方限制，网页必须登录才让下载，但是理论上是不是这样呢？我把登录后获得的链接复制到下载器是可以下载的 如果理论上支持免号下载的话，请加入此功能，一般仅用于下载别人分享的文件

是的，本工具也是获取到下载地址后就不使用账户cookie去进行下载了，不过获取下载地址必须登录（因为系统必须知道谁分享的资源 谁下载的资源）

**Comment by otokaze** [comment]
> 官方版太肥了，非常费电，而且背景是纯白色 对于眼睛和OLED屏幕造成损伤比较大 添加并检测系统色，亮色和暗色（纯黑色），可以帮助OLED屏幕省电 请将最高SDK API定为Android 13/14，我不喜欢sdcard目录被一堆垃圾中国App自动创建一堆文件夹 @otokaze 它支持多个文件同时下载吗？官方的只有一次只能同时下载一个文件，遇到那种小文件批量下载会损失不少等待下一文件进入下载队列的时间，同时下载2/3/4/5/自定义，如果网络稳定且网速够高的话，总之就是避免下载的文件是损坏的 还有开启省电模式和电池优化并息屏的后台下载，包括通知栏进度条 自带英文，因为一般中文汉字占用的像素会比英文字母多 发布至Github与F-Droid开源应用商店 它能批量下载别人分享的文件吗？我手机端网页只允许下载一个 允许复制单个下载任务的URL网页链接到其他下载管理器，比如FDM，IDM

android版本可以自己编译 ，开发者不进行额外支持。
