### ISSUE TITLE
临时文件不能自动清除

### ISSUE THREAD

**Issue by Bobxyo** [otokaze/189Cloud-Downloader#9]
在Windows 11下和Debian11下使用6线程下载，临时文件大小下载的大小相同，C盘很快就满了，不会合并后自动清除

**Comment by otokaze** [comment]
@Bobxyo 文件下载完成后会自动合并的，同时也会删除中间过程文件。你可以尝试换几个文件下载，确定是否有这个问题并提交你更多的信息作为反馈。
